sudo: false
language: php

addons:
  ssh_known_hosts: 23.239.25.212

script: php -v

before_deploy:
- openssl aes-256-cbc -K $encrypted_b8150c751d3e_key -iv $encrypted_b8150c751d3e_iv
  -in hp_deploy_rsa.enc -out hp_deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/hp_deploy_rsa
- ssh-add /tmp/hp_deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/src deploy@23.239.25.212:/home/deploy/$TRAVIS_BRANCH-files
  on:
    all_branches: true
